-- Taalreis backend schema (v3)
-- Safe to run multiple times in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  avatar_url text,
  interface_language text not null default 'nl' check (interface_language in ('nl', 'en')),
  level text not null default 'B1',
  notifications_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.journey_chapters (
  id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  chapter_number text not null,
  title text not null,
  subtitle text not null default '',
  progress_percent integer not null default 0 check (progress_percent >= 0 and progress_percent <= 100),
  total_words integer not null default 0 check (total_words >= 0),
  is_done boolean not null default false,
  is_active boolean not null default false,
  sort_order integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);

-- Keep PK migration non-destructive: older databases may have FKs depending on the existing PK.
-- We avoid dropping/recreating the primary key in this script to prevent SQL Editor failures.
-- Instead, ensure we still have a uniqueness guarantee on (user_id, id) for app-level lookups.
create unique index if not exists journey_chapters_user_id_id_idx
  on public.journey_chapters (user_id, id);
alter table public.journey_chapters add column if not exists subtitle text not null default '';

create unique index if not exists journey_chapters_user_sort_order_idx
  on public.journey_chapters (user_id, sort_order);

-- Persistent vocabulary cards per chapter.
-- Mirrors LIBRARY_VOCAB_BY_CHAPTER_KEY local state so users keep cards across devices.
create table if not exists public.chapter_vocabulary_cards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  chapter_id text not null,
  source_term text not null,
  target_term text not null,
  sort_order integer not null default 1 check (sort_order >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chapter_vocabulary_cards_user_chapter_fk
    foreign key (user_id, chapter_id)
    references public.journey_chapters(user_id, id)
    on delete cascade
);

create index if not exists chapter_vocabulary_cards_user_chapter_idx
  on public.chapter_vocabulary_cards (user_id, chapter_id);

create unique index if not exists chapter_vocabulary_cards_user_chapter_sort_order_idx
  on public.chapter_vocabulary_cards (user_id, chapter_id, sort_order);

-- Reading practice history generated by OpenAI.
-- Mirrors READING_HISTORY_KEY local state (including answers and self-evaluation).
create table if not exists public.reading_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  chapter_id text not null,
  chapter_label text not null,
  status text not null default 'active' check (status in ('active', 'completed')),
  duration_minutes integer not null check (duration_minutes > 0),
  level text not null,
  story_title text not null,
  story text not null,
  questions jsonb not null default '[]'::jsonb,
  answers jsonb not null default '{}'::jsonb,
  self_scores jsonb not null default '{}'::jsonb,
  score numeric(5,2),
  checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reading_attempts_user_chapter_fk
    foreign key (user_id, chapter_id)
    references public.journey_chapters(user_id, id)
    on delete cascade,
  constraint reading_attempts_questions_array check (jsonb_typeof(questions) = 'array'),
  constraint reading_attempts_answers_object check (jsonb_typeof(answers) = 'object'),
  constraint reading_attempts_self_scores_object check (jsonb_typeof(self_scores) = 'object')
);

create index if not exists reading_attempts_user_created_at_idx
  on public.reading_attempts (user_id, created_at desc);

create index if not exists reading_attempts_user_chapter_idx
  on public.reading_attempts (user_id, chapter_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists set_journey_chapters_updated_at on public.journey_chapters;
create trigger set_journey_chapters_updated_at
before update on public.journey_chapters
for each row
execute function public.set_updated_at();

drop trigger if exists set_chapter_vocabulary_cards_updated_at on public.chapter_vocabulary_cards;
create trigger set_chapter_vocabulary_cards_updated_at
before update on public.chapter_vocabulary_cards
for each row
execute function public.set_updated_at();

drop trigger if exists set_reading_attempts_updated_at on public.reading_attempts;
create trigger set_reading_attempts_updated_at
before update on public.reading_attempts
for each row
execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.journey_chapters enable row level security;
alter table public.chapter_vocabulary_cards enable row level security;
alter table public.reading_attempts enable row level security;

drop policy if exists "Profiles are readable by owner" on public.profiles;
create policy "Profiles are readable by owner"
  on public.profiles
  for select
  using (auth.uid() = user_id);

drop policy if exists "Profiles are writable by owner" on public.profiles;
create policy "Profiles are writable by owner"
  on public.profiles
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Journey chapters are readable by owner" on public.journey_chapters;
create policy "Journey chapters are readable by owner"
  on public.journey_chapters
  for select
  using (auth.uid() = user_id);

drop policy if exists "Journey chapters are writable by owner" on public.journey_chapters;
create policy "Journey chapters are writable by owner"
  on public.journey_chapters
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Chapter vocabulary cards are readable by owner" on public.chapter_vocabulary_cards;
create policy "Chapter vocabulary cards are readable by owner"
  on public.chapter_vocabulary_cards
  for select
  using (auth.uid() = user_id);

drop policy if exists "Chapter vocabulary cards are writable by owner" on public.chapter_vocabulary_cards;
create policy "Chapter vocabulary cards are writable by owner"
  on public.chapter_vocabulary_cards
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Reading attempts are readable by owner" on public.reading_attempts;
create policy "Reading attempts are readable by owner"
  on public.reading_attempts
  for select
  using (auth.uid() = user_id);

drop policy if exists "Reading attempts are writable by owner" on public.reading_attempts;
create policy "Reading attempts are writable by owner"
  on public.reading_attempts
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
