-- Taalreis backend schema (v4)
-- Safe to run multiple times in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  avatar_url text,
  interface_language text not null default 'nl' check (interface_language in ('nl', 'en')),
  level text not null default 'B1',
  notifications_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.account_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  slug text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint account_profiles_user_name_unique unique (user_id, name),
  constraint account_profiles_user_slug_unique unique (user_id, slug)
);

create unique index if not exists account_profiles_single_default_per_user_idx
  on public.account_profiles (user_id)
  where is_default;

create table if not exists public.account_profile_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  active_profile_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.journey_chapters (
  id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  profile_id uuid,
  chapter_number text not null,
  title text not null,
  subtitle text not null default '',
  progress_percent integer not null default 0 check (progress_percent >= 0 and progress_percent <= 100),
  total_words integer not null default 0 check (total_words >= 0),
  is_done boolean not null default false,
  is_active boolean not null default false,
  sort_order integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);

-- Keep PK migration non-destructive: older databases may have FKs depending on the existing PK.
-- We avoid dropping/recreating the primary key in this script to prevent SQL Editor failures.
-- Instead, ensure we still have a uniqueness guarantee on (user_id, id) for app-level lookups.
create unique index if not exists journey_chapters_user_id_id_idx
  on public.journey_chapters (user_id, id);
alter table public.journey_chapters add column if not exists subtitle text not null default '';
alter table public.journey_chapters add column if not exists profile_id uuid;

-- Persistent vocabulary cards per chapter.
-- Mirrors LIBRARY_VOCAB_BY_CHAPTER_KEY local state so users keep cards across devices.
create table if not exists public.chapter_vocabulary_cards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  profile_id uuid,
  chapter_id text not null,
  source_term text not null,
  target_term text not null,
  sort_order integer not null default 1 check (sort_order >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.chapter_vocabulary_cards add column if not exists profile_id uuid;

-- Reading practice history generated by OpenAI.
-- Mirrors READING_HISTORY_KEY local state (including answers and self-evaluation).
create table if not exists public.reading_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  profile_id uuid,
  chapter_id text not null,
  chapter_label text not null,
  status text not null default 'active' check (status in ('active', 'completed')),
  duration_minutes integer not null check (duration_minutes > 0),
  level text not null,
  story_title text not null,
  story text not null,
  questions jsonb not null default '[]'::jsonb,
  answers jsonb not null default '{}'::jsonb,
  self_scores jsonb not null default '{}'::jsonb,
  score numeric(5,2),
  checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reading_attempts_questions_array check (jsonb_typeof(questions) = 'array'),
  constraint reading_attempts_answers_object check (jsonb_typeof(answers) = 'object'),
  constraint reading_attempts_self_scores_object check (jsonb_typeof(self_scores) = 'object')
);
alter table public.reading_attempts add column if not exists profile_id uuid;

-- Backfill one default account profile per user.
insert into public.account_profiles (user_id, name, slug, is_default)
select p.user_id, 'Default', 'default', true
from public.profiles p
on conflict (user_id, slug) do update
set is_default = true;

-- Backfill profile references for existing user-scoped rows.
update public.journey_chapters jc
set profile_id = ap.id
from public.account_profiles ap
where jc.profile_id is null
  and ap.user_id = jc.user_id
  and ap.is_default = true;

update public.chapter_vocabulary_cards cvc
set profile_id = ap.id
from public.account_profiles ap
where cvc.profile_id is null
  and ap.user_id = cvc.user_id
  and ap.is_default = true;

update public.reading_attempts ra
set profile_id = ap.id
from public.account_profiles ap
where ra.profile_id is null
  and ap.user_id = ra.user_id
  and ap.is_default = true;

-- Ensure active profile state exists for every user and points at the default profile.
insert into public.account_profile_state (user_id, active_profile_id)
select ap.user_id, ap.id
from public.account_profiles ap
where ap.is_default = true
on conflict (user_id) do update
set active_profile_id = excluded.active_profile_id
where public.account_profile_state.active_profile_id is null;

-- Add FK relationships and constraints after backfill.
alter table public.account_profile_state
  drop constraint if exists account_profile_state_active_profile_id_fkey;
alter table public.account_profile_state
  add constraint account_profile_state_active_profile_id_fkey
  foreign key (active_profile_id)
  references public.account_profiles(id)
  on delete set null;

alter table public.journey_chapters
  alter column profile_id set not null,
  drop constraint if exists journey_chapters_profile_fk,
  add constraint journey_chapters_profile_fk
    foreign key (profile_id) references public.account_profiles(id) on delete cascade;

alter table public.chapter_vocabulary_cards
  alter column profile_id set not null,
  drop constraint if exists chapter_vocabulary_cards_profile_fk,
  add constraint chapter_vocabulary_cards_profile_fk
    foreign key (profile_id) references public.account_profiles(id) on delete cascade;

alter table public.reading_attempts
  alter column profile_id set not null,
  drop constraint if exists reading_attempts_profile_fk,
  add constraint reading_attempts_profile_fk
    foreign key (profile_id) references public.account_profiles(id) on delete cascade;

alter table public.chapter_vocabulary_cards
  drop constraint if exists chapter_vocabulary_cards_user_chapter_fk,
  add constraint chapter_vocabulary_cards_profile_chapter_fk
    foreign key (profile_id, chapter_id)
    references public.journey_chapters(profile_id, id)
    on delete cascade;

alter table public.reading_attempts
  drop constraint if exists reading_attempts_user_chapter_fk,
  add constraint reading_attempts_profile_chapter_fk
    foreign key (profile_id, chapter_id)
    references public.journey_chapters(profile_id, id)
    on delete cascade;

create unique index if not exists journey_chapters_profile_id_id_idx
  on public.journey_chapters (profile_id, id);

create unique index if not exists journey_chapters_profile_sort_order_idx
  on public.journey_chapters (profile_id, sort_order);

create index if not exists chapter_vocabulary_cards_profile_chapter_idx
  on public.chapter_vocabulary_cards (profile_id, chapter_id);

create unique index if not exists chapter_vocabulary_cards_profile_chapter_sort_order_idx
  on public.chapter_vocabulary_cards (profile_id, chapter_id, sort_order);

create index if not exists reading_attempts_profile_created_at_idx
  on public.reading_attempts (profile_id, created_at desc);

create index if not exists reading_attempts_profile_chapter_idx
  on public.reading_attempts (profile_id, chapter_id);

create or replace function public.prevent_deleting_only_account_profile()
returns trigger
language plpgsql
as $$
begin
  if (
    select count(*)
    from public.account_profiles ap
    where ap.user_id = old.user_id
  ) <= 1 then
    raise exception 'cannot delete the only profile for a user';
  end if;

  return old;
end;
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists prevent_deleting_only_account_profile_trigger on public.account_profiles;
create trigger prevent_deleting_only_account_profile_trigger
before delete on public.account_profiles
for each row
execute function public.prevent_deleting_only_account_profile();

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists set_account_profiles_updated_at on public.account_profiles;
create trigger set_account_profiles_updated_at
before update on public.account_profiles
for each row
execute function public.set_updated_at();

drop trigger if exists set_account_profile_state_updated_at on public.account_profile_state;
create trigger set_account_profile_state_updated_at
before update on public.account_profile_state
for each row
execute function public.set_updated_at();

drop trigger if exists set_journey_chapters_updated_at on public.journey_chapters;
create trigger set_journey_chapters_updated_at
before update on public.journey_chapters
for each row
execute function public.set_updated_at();

drop trigger if exists set_chapter_vocabulary_cards_updated_at on public.chapter_vocabulary_cards;
create trigger set_chapter_vocabulary_cards_updated_at
before update on public.chapter_vocabulary_cards
for each row
execute function public.set_updated_at();

drop trigger if exists set_reading_attempts_updated_at on public.reading_attempts;
create trigger set_reading_attempts_updated_at
before update on public.reading_attempts
for each row
execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.account_profiles enable row level security;
alter table public.account_profile_state enable row level security;
alter table public.journey_chapters enable row level security;
alter table public.chapter_vocabulary_cards enable row level security;
alter table public.reading_attempts enable row level security;

drop policy if exists "Profiles are readable by owner" on public.profiles;
create policy "Profiles are readable by owner"
  on public.profiles
  for select
  using (auth.uid() = user_id);

drop policy if exists "Profiles are writable by owner" on public.profiles;
create policy "Profiles are writable by owner"
  on public.profiles
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Account profiles are readable by owner" on public.account_profiles;
create policy "Account profiles are readable by owner"
  on public.account_profiles
  for select
  using (auth.uid() = user_id);

drop policy if exists "Account profiles are writable by owner" on public.account_profiles;
create policy "Account profiles are writable by owner"
  on public.account_profiles
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Account profile state is readable by owner" on public.account_profile_state;
create policy "Account profile state is readable by owner"
  on public.account_profile_state
  for select
  using (auth.uid() = user_id);

drop policy if exists "Account profile state is writable by owner" on public.account_profile_state;
create policy "Account profile state is writable by owner"
  on public.account_profile_state
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Journey chapters are readable by owner" on public.journey_chapters;
create policy "Journey chapters are readable by owner"
  on public.journey_chapters
  for select
  using (
    exists (
      select 1
      from public.account_profiles ap
      where ap.id = journey_chapters.profile_id
        and ap.user_id = auth.uid()
    )
  );

drop policy if exists "Journey chapters are writable by owner" on public.journey_chapters;
create policy "Journey chapters are writable by owner"
  on public.journey_chapters
  for all
  using (
    exists (
      select 1
      from public.account_profiles ap
      where ap.id = journey_chapters.profile_id
        and ap.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.account_profiles ap
      where ap.id = journey_chapters.profile_id
        and ap.user_id = auth.uid()
    )
  );

drop policy if exists "Chapter vocabulary cards are readable by owner" on public.chapter_vocabulary_cards;
create policy "Chapter vocabulary cards are readable by owner"
  on public.chapter_vocabulary_cards
  for select
  using (
    exists (
      select 1
      from public.account_profiles ap
      where ap.id = chapter_vocabulary_cards.profile_id
        and ap.user_id = auth.uid()
    )
  );

drop policy if exists "Chapter vocabulary cards are writable by owner" on public.chapter_vocabulary_cards;
create policy "Chapter vocabulary cards are writable by owner"
  on public.chapter_vocabulary_cards
  for all
  using (
    exists (
      select 1
      from public.account_profiles ap
      where ap.id = chapter_vocabulary_cards.profile_id
        and ap.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.account_profiles ap
      where ap.id = chapter_vocabulary_cards.profile_id
        and ap.user_id = auth.uid()
    )
  );

drop policy if exists "Reading attempts are readable by owner" on public.reading_attempts;
create policy "Reading attempts are readable by owner"
  on public.reading_attempts
  for select
  using (
    exists (
      select 1
      from public.account_profiles ap
      where ap.id = reading_attempts.profile_id
        and ap.user_id = auth.uid()
    )
  );

drop policy if exists "Reading attempts are writable by owner" on public.reading_attempts;
create policy "Reading attempts are writable by owner"
  on public.reading_attempts
  for all
  using (
    exists (
      select 1
      from public.account_profiles ap
      where ap.id = reading_attempts.profile_id
        and ap.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.account_profiles ap
      where ap.id = reading_attempts.profile_id
        and ap.user_id = auth.uid()
    )
  );
